In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_excel("C:/Users/archi/OneDrive/Documents/report-cs.xlsx")
df.head()

,Category,Ticket Id,Due by Time,Impact,Item,Priority,Status,Sub-Category,Type,Close Notes,Closed Time,Created Time,Department
0,Vulnarability Management,37383,2025-04-03 14:00:00,Medium,Report,Medium,Closed,Scheduled Task,Service Request,Report has been reviewed and remediation proje...,2025-05-13 06:50:01,2025-04-01 06:00:54,Cybersecurity
1,Monitoring,37384,2025-04-11 08:00:12,Low,Report,Low,Closed,Scheduled Task,Service Request,Report has been generated and reviewed,2025-04-03 10:04:13,2025-04-01 06:01:00,Cybersecurity
2,Monitoring,37385,2025-04-11 08:00:34,Low,Report,Low,Closed,Scheduled Task,Service Request,Awareness campaign is currently running,2025-04-29 08:08:17,2025-04-01 06:01:05,Cybersecurity
3,Info & Event Management,37386,2025-04-03 14:00:00,Medium,Benign,Medium,Closed,Incident,Incident,Nothing suspicious found. Detailed investigati...,2025-04-02 05:30:19,2025-04-01 06:40:49,Cybersecurity
4,Email Sec,37389,2025-04-11 08:00:00,Low,Benign,Low,Closed,Incident,Incident,Nothing suspicious found. Detailed investigati...,2025-04-02 05:32:26,2025-04-01 07:32:37,Cybersecurity

In [4]:
df["Type"].value_counts()

Type
Incident           1127
Service Request      75
Name: count, dtype: int64

In [5]:
df.columns

Index(['Category', 'Ticket Id', 'Due by Time', 'Impact', 'Item', 'Priority',
       'Status', 'Sub-Category', 'Type', 'Close Notes', 'Closed Time',
       'Created Time', 'Department'],
      dtype='object')

In [6]:
working_df=df.drop(["Department","Status","Ticket Id"],axis=1)

In [7]:
working_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1202 entries, 0 to 1201
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      1202 non-null   object
 1   Due by Time   1202 non-null   datetime64[ns]
 2   Impact        1202 non-null   object
 3   Item          1202 non-null   object
 4   Priority      1202 non-null   object
 5   Sub-Category  705 non-null    object
 6   Type          1202 non-null   object
 7   Close Notes   646 non-null    object
 8   Closed Time   1173 non-null   datetime64[ns]
 9   Created Time  1202 non-null   datetime64[ns]
dtypes: datetime64[ns](3), object(7)
memory usage: 94.0+ KB

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
working_df['Impact'] = le.fit_transform(working_df['Impact'])
mapping = {label: i for i, label in enumerate(le.classes_)}
print(mapping)

{'High': 0, 'Low': 1, 'Medium': 2}

In [9]:
working_df["Category"]=le.fit_transform(working_df["Category"])
mapping = {label: i for i, label in enumerate(le.classes_)}
print(mapping)

{'Backup Management': 0, 'Cast': 1, 'Check': 2, 'Cloud Security': 3, 'Data Security': 4, 'Email Sec': 5, 'External': 6, 'Info & Event Management': 7, 'Infrastructure': 8, 'Internet': 9, 'License Management': 10, 'Monitoring': 11, 'PAM': 12, 'Patch Management': 13, 'Servers': 14, 'Tool': 15, 'Vulnarability Management': 16, 'Zoom': 17}

In [10]:
working_df["Type"]=le.fit_transform(working_df["Type"])
mapping = {label: i for i, label in enumerate(le.classes_)}
print(mapping)

{'Incident': 0, 'Service Request': 1}

In [11]:
working_df["Item"]=le.fit_transform(working_df["Item"])
mapping = {label: i for i, label in enumerate(le.classes_)}
print(mapping)

{'Benign': 0, 'False Positive': 1, 'Report': 2, 'True Positive': 3, 'Wireless': 4}

In [12]:
working_df["Priority"]=le.fit_transform(working_df["Priority"])
mapping = {label: i for i, label in enumerate(le.classes_)}
print(mapping)

{'High': 0, 'Low': 1, 'Medium': 2, 'Urgent': 3}

In [13]:
working_df["Sub-Category"] = working_df["Sub-Category"].fillna("Unknown")

In [14]:
working_df["Sub-Category"]=le.fit_transform(working_df["Sub-Category"])
mapping = {label: i for i, label in enumerate(le.classes_)} 
print(mapping)

{'Access': 0, 'Adhoc Task': 1, 'Connectivity': 2, 'Incident': 3, 'Issue': 4, 'Permit': 5, 'Reports': 6, 'Rrequest': 7, 'Scheduled Task': 8, 'Service Request': 9, 'Spam': 10, 'Unknown': 11, 'Zoom Room': 12}

In [15]:
# No missing values in the dataset from all the above fields.
working_df['Sub-Category'].isnull().sum()

np.int64(0)

In [16]:
# No missing values in the dataset in datetime fields.
working_df['Closed Time'].isnull().sum()

np.int64(29)

In [17]:
working_df['Close Notes'].isnull().sum()

np.int64(556)

In [18]:
working_df.head()

,Category,Due by Time,Impact,Item,Priority,Sub-Category,Type,Close Notes,Closed Time,Created Time
0,16,2025-04-03 14:00:00,2,2,2,8,1,Report has been reviewed and remediation proje...,2025-05-13 06:50:01,2025-04-01 06:00:54
1,11,2025-04-11 08:00:12,1,2,1,8,1,Report has been generated and reviewed,2025-04-03 10:04:13,2025-04-01 06:01:00
2,11,2025-04-11 08:00:34,1,2,1,8,1,Awareness campaign is currently running,2025-04-29 08:08:17,2025-04-01 06:01:05
3,7,2025-04-03 14:00:00,2,0,2,3,0,Nothing suspicious found. Detailed investigati...,2025-04-02 05:30:19,2025-04-01 06:40:49
4,5,2025-04-11 08:00:00,1,0,1,3,0,Nothing suspicious found. Detailed investigati...,2025-04-02 05:32:26,2025-04-01 07:32:37

In [19]:
sentiment=working_df['Close Notes']
sentiment = sentiment.fillna('')
sentiment=sentiment.astype(str).tolist()

In [20]:
working_df['Close Notes']

0       Report has been reviewed and remediation proje...
1                 Report has been generated and reviewed
2                Awareness campaign is currently running
3       Nothing suspicious found. Detailed investigati...
4       Nothing suspicious found. Detailed investigati...
                              ...
1197                                                  NaN
1198                                                  NaN
1199    The memory usage on the virtual machine improv...
1200                                                  NaN
1201                Jumpcloud is not being used in Jasper
Name: Close Notes, Length: 1202, dtype: object

In [21]:
from transformers import BertTokenizer, BertModel
import torch
import numpy as np

# Load pretrained BERT
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Set model to evaluation mode
model.eval()

def get_embeddings(text_list, max_length=128):
    """
    Convert list of texts into BERT embeddings
    """
    embeddings = []

    for text in text_list:
        inputs = tokenizer(
            str(text),
            return_tensors="pt",
            truncation=True,
            padding='max_length',
            max_length=max_length
        )

        with torch.no_grad():
            outputs = model(**inputs)

        # Take CLS token (sentence representation)
        cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()
        embeddings.append(cls_embedding)

    return np.array(embeddings)

In [22]:
text_embeddings = get_embeddings(sentiment)

print(text_embeddings.shape)

(1202, 768)

In [23]:
text_embeddings.dtype

dtype('float32')

In [24]:
text_embeddings[0]

array([-8.30107152e-01, -4.42383528e-01, -5.07341437e-02, -3.68637890e-01,
       -4.38057214e-01, -5.93480431e-02, -6.82433993e-02,  3.44042033e-01,
       -2.52937436e-01, -2.06603855e-01,  4.52769026e-02, -4.20376509e-01,
       -1.24977507e-01,  4.89268780e-01, -2.10076869e-01,  1.20543391e-02,
        4.64946311e-03,  4.42327231e-01,  1.52692690e-01,  4.25463989e-02,
       -8.40394422e-02, -5.26023924e-01,  1.40011981e-01, -1.06716625e-01,
       -1.77533776e-01, -1.36083156e-01,  9.33827832e-02,  1.70219392e-02,
       -2.65870214e-01,  6.07880056e-02,  1.28149152e-01,  5.08540750e-01,
       -5.75041413e-01, -2.18219191e-01,  2.94052690e-01, -1.34010524e-01,
        1.45496920e-01,  3.74541938e-01,  2.16487572e-01,  1.80349231e-01,
        9.01996791e-02, -4.96996269e-02, -8.70419666e-02, -4.57137786e-02,
       -3.15608382e-02, -1.43780261e-01, -2.78180814e+00,  3.31043303e-01,
       -6.07812405e-01, -3.47558931e-02,  5.00390828e-01,  1.90408528e-01,
        5.83723187e-01,  4.18093763e-02, -1.54032528e-01,  6.26237035e-01,
       -3.29946458e-01, -4.64641005e-02,  2.89366931e-01,  5.29116452e-01,
        7.19420686e-02, -4.94106770e-01,  1.83397546e-01, -5.92711605e-02,
        1.93841338e-01,  3.22091490e-01, -1.46155238e-01,  3.59259158e-01,
       -2.58416891e-01,  2.92613834e-01, -8.28949749e-01,  2.04567425e-02,
        4.96150643e-01,  3.11594248e-01, -1.40833884e-01, -6.40634537e-01,
        1.38004348e-01,  2.66298831e-01, -3.94643873e-01, -3.57508719e-01,
        3.38523716e-01,  4.78354961e-01, -2.06055284e-01, -1.94830552e-01,
        1.56466186e-01,  7.87104547e-01, -7.66723454e-02, -5.58156610e-01,
       -4.69404340e-01,  4.62025404e-01,  8.94266963e-02,  1.73460543e-02,
        6.04973957e-02,  3.36836636e-01, -5.94612621e-02,  3.29957426e-01,
        1.42009526e-01,  3.21377695e-01,  3.78480643e-01,  1.42022297e-02,
        2.17685968e-01,  3.63786519e-01,  1.91747740e-01,  9.04729776e-03,
        2.38057286e-01, -2.65815467e-01, -3.94253582e-01, -2.33051181e-03,
       -1.61184892e-01, -2.09672427e+00,  3.42509538e-01,  2.57922947e-01,
        1.18933201e-01, -5.71206212e-01, -6.55270100e-01,  5.89656830e-01,
        7.90542185e-01,  6.53179809e-02,  2.90937573e-02,  4.22395259e-01,
       -1.06008135e-01,  5.55418491e-01, -1.74430102e-01,  3.66542280e-01,
       -2.45191813e-01,  7.18952894e-01,  5.82231164e-01,  2.67235875e-01,
        4.14461911e-01,  6.81755364e-01,  6.74177036e-02,  7.02541888e-01,
       -4.10882354e-01, -3.81846368e-01, -1.69500798e-01,  7.46632293e-02,
        4.69093382e-01, -2.69244462e-01, -3.40064883e-01, -7.92342052e-02,
       -8.84349823e-01, -5.67155957e-01, -2.28007174e+00,  4.16490495e-01,
        5.47226429e-01,  2.52717793e-01, -5.46166658e-01,  4.58931997e-02,
        2.73342133e-01, -1.85727403e-02,  6.40629113e-01, -7.72051215e-02,
       -3.54744673e-01, -2.40834892e-01, -1.43591404e-01,  2.12579936e-01,
       -4.60380256e-01, -3.72577190e-01,  3.08674797e-02,  8.76510680e-01,
        2.52487838e-01,  1.80602133e-01, -5.69727123e-02, -3.53150070e-04,
       -3.99348438e-01, -8.93772990e-02,  5.87907061e-02,  4.26832646e-01,
        3.98873627e-01, -2.53363758e-01, -2.25074366e-01, -2.75659598e-02,
        4.93257433e-01, -4.55031991e-01,  5.76329112e-01, -2.79665440e-01,
        2.75076658e-01,  1.36001155e-01, -2.34771758e-01,  4.90261689e-02,
       -4.83436048e-01,  4.33398306e-01, -2.58920670e-01,  7.01141357e-01,
        4.73875761e-01, -5.18368423e-01,  3.85062754e-01,  2.76244193e-01,
       -9.97328907e-02,  5.51860332e-01, -1.23186700e-01, -1.77183464e-01,
       -3.16640437e-01,  5.00465930e-01,  7.75364757e-01,  2.24783421e-01,
        4.81835008e-01, -5.61835349e-01,  1.65514145e-02,  3.65682304e-01,
        2.27595150e-01,  4.33908217e-02, -2.58041322e-01,  3.29500049e-01,
       -7.81883657e-01,  2.98480034e+00,  5.02924204e-01, -1.31752461e-01,
       -3.91639680e-01,  2.27087021e-01,  2.35136136e-01,  2.01010972e-01,
       -1.87454596e-01, -5.86622953e-01,  8.92468244e-02,  1.08483732e-01,
        6.97434127e-01, -1.25982910e-02, -2.17619047e-01, -2.83230245e-01,
        1.89188242e-01,  2.82892525e-01, -2.27222010e-01,  8.62996459e-01,
       -2.99273491e-01, -4.02336091e-01, -1.30490437e-02,  4.81274039e-01,
       -3.95867378e-01, -1.53158772e+00,  5.46235085e-01,  3.15890372e-01,
       -1.67189091e-01,  2.76082426e-01, -5.71669579e-01, -4.27696139e-01,
       -2.95226008e-01, -4.08955634e-01,  3.66255417e-02, -1.61993757e-01,
       -5.41524515e-02,  5.19666314e-01,  5.55931926e-01, -2.63472386e-02,
        3.04844439e-01,  4.01819289e-01,  4.02299166e-01,  5.75758517e-03,
        2.04766363e-01,  7.88610578e-02,  3.48520845e-01, -5.46114482e-02,
        3.09119225e-01, -7.30293632e-01,  1.81107223e-03, -3.53162855e-01,
        5.88600338e-01, -2.81359792e-01, -3.43956858e-01,  2.09983103e-02,
       -6.20107539e-02, -1.62216067e-01,  5.24340808e-01, -1.23718254e-01,
       -3.22977901e-01, -5.22591412e-01,  3.96906972e-01, -4.28136349e-01,
       -6.26045048e-01, -5.96278310e-01,  6.85135126e-01, -4.11397591e-02,
       -3.26152474e-01, -2.60414076e+00, -3.18777174e-01, -1.32573962e-01,
        4.88445640e-01,  4.02461849e-02, -5.84151924e-01, -2.48423845e-01,
        5.36022425e-01,  2.81332642e-01, -6.92503512e-01,  3.36839676e-01,
        2.93274760e-01,  3.59897375e-01, -1.53081298e-01, -1.10298224e-01,
        1.84556186e-01,  5.72078526e-02, -5.82134485e-01, -3.87773633e-01,
       -4.46177348e-02, -1.00193955e-01,  1.20994568e-01, -2.19673485e-01,
       -1.74574435e-01, -3.47416043e-01,  4.48429585e-02, -3.59613858e-02,
       -2.53549218e-01,  2.96480864e-01, -4.53915119e-01, -9.16158110e-02,
       -6.92435145e-01,  2.24844098e-01, -2.15824679e-01,  1.08295523e-01,
       -3.78974724e+00,  1.30301118e-01, -1.77930281e-01,  5.46337068e-02,
       -1.07905202e-01, -5.74380010e-02,  6.52611792e-01,  1.19129226e-01,
       -5.30597985e-01,  2.50919580e-01,  2.80797094e-01, -1.43410012e-01,
        6.95898414e-01,  8.64446700e-01,  7.14611709e-01,  7.33689129e-01,
        5.01263261e-01, -1.42227858e-01,  5.48255980e-01,  1.01933599e-01,
        3.27193379e-01, -6.56009078e-01, -3.11614305e-01, -3.98973376e-01,
        4.52570647e-01,  3.86204392e-01, -4.53615904e-01,  5.18496156e-01,
       -3.72920573e-01,  1.47310168e-01,  3.01340580e-01, -9.74474177e-02,
       -1.01394936e-01, -2.22135201e-01, -6.98578119e-01,  3.86404321e-02,
        1.52321547e-01,  3.62282246e-01, -2.68189460e-01, -1.35056257e-01,
       -9.68789384e-02,  1.56134963e-01,  4.77075577e-04,  4.38795388e-01,
        8.76670301e-01,  3.93652737e-01,  1.87314227e-01,  7.94147849e-02,
       -2.66795427e-01,  1.59027383e-01, -2.66913533e-01, -1.13715708e-01,
        7.77342856e-01, -2.31162518e-01, -7.18645751e-02, -9.67434198e-02,
        5.95104218e-01, -3.87542516e-01, -3.10054660e-01,  1.17308684e-01,
        5.63230455e-01, -4.49127853e-01,  5.53232074e-01, -1.75220981e-01,
        1.83767125e-01, -2.84894764e-01,  8.33369613e-01, -5.25592089e-01,
        5.99734634e-02,  2.15647742e-02,  1.02802843e-01,  9.69251156e-01,
       -3.25083822e-01, -1.09413671e+00, -4.89070892e-01, -4.34688330e-01,
       -2.49905825e-01, -1.78106055e-02,  4.44039822e-01, -6.70269132e-02,
       -7.20885873e-01, -3.54155123e-01, -4.06523347e-01,  8.45892787e-01,
       -1.92435831e-01,  3.63344371e-01,  8.20775688e-01, -1.37380794e-01,
       -1.11640859e+00, -3.94458264e-01, -1.68141752e-01, -1.46838561e-01,
        3.91327232e-01,  4.08603638e-01, -1.15140021e-01,  1.59827501e-01,
        7.68005490e-01, -9.27940249e-01,  3.79725806e-02, -5.57559609e-01,
       -2.59385884e-01, -4.67005312e-01, -3.49784046e-01,  8.37161392e-02,
        2.01692566e-01, -5.03720701e-01, -3.98393661e-01,  1.40905157e-01,
       -4.42516506e-02,  1.12070240e-01, -5.26468232e-02, -6.56150341e-01,
        7.42632389e-01,  1.81724712e-01,  9.78519619e-01,  7.47959733e-01,
        2.68089235e-01,  9.91973579e-01,  3.33119780e-01,  7.64236391e-01,
        6.90486670e-01, -1.86385632e-01,  4.05749321e-01, -1.57728791e-04,
       -2.65404314e-01, -1.88693643e-01, -2.08712846e-01, -1.57068998e-01,
       -3.94645840e-01,  1.00969508e-01,  3.46344471e-01,  7.55723566e-02,
       -5.28054774e-01, -6.22431993e-01,  3.42367113e-01, -4.08047080e-01,
       -6.73164010e-01,  4.09020841e-01,  3.62102360e-01,  2.22252265e-01,
        2.09493283e-02, -4.43168491e-01, -6.68832302e-01, -8.34240168e-02,
        4.65775818e-01,  4.11263287e-01, -2.95973748e-01, -2.39617959e-01,
       -1.80506766e-01,  6.52117252e-01, -3.32744300e-01, -8.62941384e-01,
       -4.64170456e-01, -7.74834603e-02,  8.48570317e-02, -1.97820693e-01,
        1.84565932e-01, -1.20478541e-01, -8.42608213e-02, -1.31295592e-01,
       -3.74740273e-01,  3.44953179e-01, -1.58865213e+00, -5.90825304e-02,
        2.71115899e-01,  8.62568915e-02,  2.03463048e-01, -5.42353511e-01,
       -8.13808680e-01,  1.20802951e+00,  2.19041854e-01,  3.94559681e-01,
       -2.99899280e-01, -6.44965246e-02,  1.31433502e-01, -2.67094642e-01,
        1.14370920e-02,  2.56598264e-01, -4.70298007e-02, -2.56334953e-02,
       -4.30186540e-01,  8.01339597e-02, -2.37762883e-01,  8.24916601e-01,
        6.13882065e-01,  2.69072771e-01,  2.96294913e-02, -3.67767245e-01,
        2.69377738e-01,  5.18311799e-01,  7.70113096e-02,  4.52990055e-01,
        1.22288063e-01, -8.36903751e-02, -4.74226832e-01, -3.23661029e-01,
        2.52460957e-01,  3.96224439e-01,  3.41938138e-01, -3.80887628e-01,
        7.72115469e-01,  3.00486505e-01,  1.32285029e-01,  5.67208171e-01,
        1.67345285e-01, -3.16446602e-01,  2.36368120e-01,  3.24688554e-01,
       -3.79710913e-01,  3.54758680e-01,  2.74283230e-01, -3.98733392e-02,
       -4.96909797e-01, -2.22804397e-01,  1.09347560e-01, -2.31365263e-01,
        7.13209391e-01, -5.68414450e-01, -6.84296861e-02,  1.56199828e-01,
       -6.66166663e-01,  3.83471809e-02,  1.29022002e-02, -4.45028901e-01,
       -7.14022219e-01, -5.47751546e-01,  1.26600908e-02, -8.60703051e-01,
       -6.06932566e-02, -4.66147810e-01, -1.85942248e-01,  4.39776152e-01,
        6.57255888e-01, -6.29027933e-03, -4.70718026e-01,  5.22293568e-01,
       -6.68391764e-01,  2.31557682e-01,  1.46264389e-01,  4.52027112e-01,
       -4.12778437e-01, -1.00326270e-01,  6.98216632e-03, -9.92950797e-01,
       -4.14602786e-01,  3.03763658e-01, -3.06989580e-01,  7.14237511e-01,
       -5.96972033e-02,  3.73086631e-01, -8.27573910e-02, -9.17805880e-02,
       -3.80386919e-01, -6.44769371e-01,  1.16439097e-01,  1.10935345e-01,
        1.22608028e-01,  1.83300957e-01,  1.43622577e-01, -4.24229383e-01,
       -1.67690128e-01, -1.96340635e-01, -2.79525906e-01,  2.21035197e-01,
        5.85754991e-01,  1.16305530e-01, -4.00393791e-02,  2.76600182e-01,
        7.15742469e-01, -1.76314071e-01, -1.89166829e-01, -3.75555456e-01,
        7.29548633e-02, -3.24990243e-01, -3.81508291e-01, -8.50059018e-02,
        2.23489165e-01, -4.16961432e-01,  5.91571987e-01, -2.07048863e-01,
        1.59234238e+00,  1.07296348e+00,  2.47605383e-01,  2.56455302e-01,
        4.26910639e-01, -1.90086626e-02, -5.14328182e-01,  6.49916351e-01,
       -2.38530502e-01, -1.05360240e-01,  1.32115245e-01,  2.87281349e-04,
       -4.29683447e-01,  6.09408081e-01,  3.40934098e-01,  5.04496217e-01,
       -2.48172864e-01, -3.74517888e-01, -6.00341678e-01,  1.73283175e-01,
       -8.94034266e-01,  3.13315958e-01,  4.89745773e-02, -1.93722397e-02,
        1.03029385e-02,  5.53885162e-01,  2.18019053e-01,  1.23194970e-01,
        1.87159091e-01,  3.96455467e-01,  2.58241266e-01,  1.94320202e-01,
        6.69771135e-02,  5.05830526e-01, -6.45378292e-01, -5.46153337e-02,
       -4.74751025e-01, -1.06336214e-01,  1.06661722e-01,  1.80752911e-02,
        1.01967379e-01, -6.29011750e-01,  5.61180532e-01, -4.42636684e-02,
       -1.26892462e-01,  8.03383231e-01, -4.61437136e-01,  7.14492351e-02,
        7.78002977e-01,  5.21739900e-01, -2.19293222e-01, -3.98363769e-02,
       -3.47372860e-01,  5.42358309e-02, -3.62546802e-01, -1.48573574e-02,
       -6.82709217e-02, -2.76240528e-01, -3.09840709e-01,  9.58038941e-02,
        1.66317791e-01,  6.45793021e-01,  2.16890186e-01, -1.20695740e-01,
        3.49567086e-02,  9.25227106e-02, -3.99106771e-01,  2.45024353e-01,
        1.11364350e-01, -1.23880409e-01, -4.26963121e-01,  9.84901488e-02,
        6.76056087e-01, -5.54757938e-03,  3.47352833e-01,  1.04003083e-02,
       -7.16197416e-02,  1.36397794e-01, -2.14879572e-01, -1.81712914e+00,
        1.25003636e-01,  2.10562408e-01, -3.09699196e-02,  2.75998414e-01,
        3.80168289e-01,  1.25249475e-01,  1.60221964e-01,  3.99848700e-01,
       -2.81613261e-01,  2.19552353e-01,  5.65658331e-01,  8.99518132e-02,
       -6.35111213e-01,  2.55681694e-01,  3.45986515e-01, -5.14466912e-02,
       -1.90787598e-01, -5.03961265e-01, -3.42292011e-01, -1.47522509e-01,
        1.67666003e-01,  2.53084898e-01, -3.83168817e-01, -9.33731794e-01,
       -6.74430355e-02,  1.61267668e-01, -7.04548001e-01,  3.24773014e-01,
        1.15273511e+00, -5.49809456e-01,  2.09544033e-01,  5.57431728e-02,
        2.88278237e-02,  1.70240790e-01, -2.24552035e-01, -1.49441093e-01,
        5.73981404e-01,  1.90493628e-01, -6.34044409e-04, -4.83867675e-01,
        2.64190733e-01, -3.21952075e-01,  2.27910113e-02,  2.29139417e-01,
       -1.52610302e-01,  4.84122247e-01, -7.44570911e-01,  7.51181483e-01,
       -3.58235031e-01,  1.79566741e-01,  1.72389522e-01,  4.51889038e-01,
        1.18314750e-01,  7.57834613e-01,  5.70078045e-02,  9.17085856e-02,
        4.91844229e-02, -6.39760271e-02, -4.75998282e-01,  1.73849538e-02,
       -3.87235954e-02, -1.13851100e-01, -1.86120600e-01,  3.13708872e-01,
       -3.20091814e-01, -6.59588456e-01,  7.43312463e-02,  1.90093055e-01,
        1.67307377e-01, -4.90249902e-01, -3.56035590e-01,  4.25604045e-01,
        7.88653642e-02,  2.40011215e-02, -3.69909316e-01,  7.35159755e-01,
       -1.73387855e-01,  3.19507658e-01,  3.81578892e-01,  3.78513336e-02,
       -1.31308109e-01, -6.64883554e-01,  3.89278121e-02,  1.77656412e-01,
       -5.83337402e+00, -8.96765888e-01, -3.97300839e-01, -5.74288785e-01,
        1.79060042e-01,  1.27186492e-01, -2.06432268e-02,  2.20993072e-01,
        2.69565284e-02, -7.18275458e-02,  5.30767180e-02, -2.53989905e-01,
       -4.42057461e-01, -7.29751825e-01,  1.55709773e-01,  1.12176605e-01],
      dtype=float32)

In [25]:
working_df.shape

(1202, 10)

In [26]:
import pandas as pd

emb_df = pd.DataFrame(
    text_embeddings,
    columns=[f'emb_{i}' for i in range(text_embeddings.shape[1])]
)

In [27]:
working_df = working_df.reset_index(drop=True)
emb_df = emb_df.reset_index(drop=True)

In [28]:
working_df = pd.concat([working_df, emb_df], axis=1)

In [29]:
working_df.head()

,Category,Due by Time,Impact,Item,Priority,Sub-Category,Type,Close Notes,Closed Time,Created Time,...,emb_758,emb_759,emb_760,emb_761,emb_762,emb_763,emb_764,emb_765,emb_766,emb_767
0,16,2025-04-03 14:00:00,2,2,2,8,1,Report has been reviewed and remediation proje...,2025-05-13 06:50:01,2025-04-01 06:00:54,...,-0.020643,0.220993,0.026957,-0.071828,0.053077,-0.253990,-0.442057,-0.729752,0.155710,0.112177
1,11,2025-04-11 08:00:12,1,2,1,8,1,Report has been generated and reviewed,2025-04-03 10:04:13,2025-04-01 06:01:00,...,0.385790,0.173043,-0.056816,-0.121102,-0.085845,-0.252812,-0.323839,-0.627024,0.556212,0.069456
2,11,2025-04-11 08:00:34,1,2,1,8,1,Awareness campaign is currently running,2025-04-29 08:08:17,2025-04-01 06:01:05,...,-0.021271,0.044702,0.183708,0.203967,0.254797,-0.182468,-0.097269,-0.257415,0.159631,0.315656
3,7,2025-04-03 14:00:00,2,0,2,3,0,Nothing suspicious found. Detailed investigati...,2025-04-02 05:30:19,2025-04-01 06:40:49,...,0.046767,-0.035385,0.028578,-0.097673,-0.069007,-0.409344,-0.317140,-0.677239,0.343034,0.375820
4,5,2025-04-11 08:00:00,1,0,1,3,0,Nothing suspicious found. Detailed investigati...,2025-04-02 05:32:26,2025-04-01 07:32:37,...,0.046767,-0.035385,0.028578,-0.097673,-0.069007,-0.409344,-0.317140,-0.677239,0.343034,0.375820

In [30]:
working_df['Closing_Time']=working_df['Closed Time'] - working_df['Created Time']
working_df['time_to_close']=working_df['Closing_Time'].dt.total_seconds()

In [31]:
working_df.drop(['Created Time', 'Closed Time', 'Due by Time','Close Notes'], axis=1, inplace=True)

In [32]:
# working_df['Lateness_seconds'] = working_df['Lateness'].dt.total_seconds()
# working_df['Closing_Time_seconds'] = working_df['Closing Time'].dt.total_seconds()

In [33]:
working_df.columns

Index(['Category', 'Impact', 'Item', 'Priority', 'Sub-Category', 'Type',
       'emb_0', 'emb_1', 'emb_2', 'emb_3',
       ...
       'emb_760', 'emb_761', 'emb_762', 'emb_763', 'emb_764', 'emb_765',
       'emb_766', 'emb_767', 'Closing_Time', 'time_to_close'],
      dtype='object', length=776)

In [34]:
working_df.drop(['Closing_Time'], axis=1, inplace=True)

In [35]:
working_df["Sub_category"]=working_df["Sub-Category"]
working_df.drop("Sub-Category",axis=1,inplace=True)

In [36]:
working_df.columns

Index(['Category', 'Impact', 'Item', 'Priority', 'Type', 'emb_0', 'emb_1',
       'emb_2', 'emb_3', 'emb_4',
       ...
       'emb_760', 'emb_761', 'emb_762', 'emb_763', 'emb_764', 'emb_765',
       'emb_766', 'emb_767', 'time_to_close', 'Sub_category'],
      dtype='object', length=775)

In [37]:
X=working_df.drop('Item', axis=1)
y=working_df['Item']

In [38]:
cols = list(working_df.columns)

# columns you want to move
move_cols = ['time_to_close', 'Sub_category']

# find where emb_0 starts
emb_index = cols.index('emb_0')

# remove the columns from current position
for col in move_cols:
    cols.remove(col)

# insert them before emb_0
cols = cols[:emb_index] + move_cols + cols[emb_index:]

# reorder dataframe
working_df = working_df[cols]

In [39]:
working_df.columns

Index(['Category', 'Impact', 'Item', 'Priority', 'Type', 'time_to_close',
       'Sub_category', 'emb_0', 'emb_1', 'emb_2',
       ...
       'emb_758', 'emb_759', 'emb_760', 'emb_761', 'emb_762', 'emb_763',
       'emb_764', 'emb_765', 'emb_766', 'emb_767'],
      dtype='object', length=775)

In [42]:
working_df.to_excel("D:/NNDL/working_df.xlsx", index=False)

In [72]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric='mlogloss'
)

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.91701244813278

In [73]:
import joblib

joblib.dump(model, "API/models/security_alert.pkl")

['API/models/security_alert.pkl']